# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Codecov CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::node_modules"

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: set up env
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: test and upload to codecov
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
          TOKEN: ${{ secrets.TOKEN }}
          DATASHEET_ID: ${{ secrets.DATASHEET_ID }}
          FOLDER_ID: ${{ secrets.FOLDER_ID }}
          SPACE_ID: ${{ secrets.SPACE_ID }}
          VIEW_ID: ${{ secrets.VIEW_ID }}
        run: |
          yarn
          yarn test:coverage
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          ./codecov
